[package]
name = "smallsite"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3.72"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew.git" }

[package.metadata.wasm-pack]
out-dir = "static"